<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'udjT2s7Sw8c=');
$cfg_Cs[2]=array(0,1,1,'svrGt9W5yr4=');
$cfg_Cs[3]=array(0,1,1,'0MLOxbavzKw=');
$cfg_Cs[18]=array(0,1,1,'zbbL372o0uk=');
$cfg_Cs[6]=array(0,1,1,'s8m5prC4wP0=');
$cfg_Cs[7]=array(0,1,1,'warPtc7Sw8c=');
$cfg_Cs[8]=array(0,1,1,'ytPGtbKlt8U=');
$cfg_Cs[9]=array(3,1,1,'xvPStdDCzsU=');
$cfg_Cs[10]=array(3,1,1,'0NDStdDCzsU=');
?>