<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",47,79);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("field","",175,204);
$z[2][4]['name']="position";
$z[3]=Array("arclist"," \r\n                <li class=\"li_e\"><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n",285,436);
$z[3][4]['typeid']="2";
$z[3][4]['row']="10";
$z[3][4]['titlelen']="50";
$z[4]=Array("global","",565,597);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("field","",1723,1741);
$z[5][4]['name']="body";
$z[6]=Array("include","",1816,1853);
$z[6][4]['filename']="footer.htm";

?>