<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("arclist","     \r\n <li class=\"lie\"><a href=\"/gywm/2016/0616/14.html\">[field:image/]</a></li>\r\n",4176,4355);
$z[1][4]['row']="1";
$z[1][4]['imgwidth']="318";
$z[1][4]['imgheight']="150";
$z[1][4]['type']="image";
$z[1][4]['typeid']="1";
$z[2]=Array("arclist","\r\n      <li class=\"lie\"><a href=\"/cpzs\">[field:image/]</a></li>\r\n",4668,4829);
$z[2][4]['row']="1";
$z[2][4]['imgwidth']="318";
$z[2][4]['imgheight']="150";
$z[2][4]['type']="image";
$z[2][4]['typeid']="2";
$z[3]=Array("arclist","\r\n            <li class=\"lie\"><a href=\"/spbf/2016/0616/18.html\">[field:image/]</a></li>\r\n",5142,5327);
$z[3][4]['row']="1";
$z[3][4]['imgwidth']="318";
$z[3][4]['imgheight']="150";
$z[3][4]['type']="image";
$z[3][4]['typeid']="8";
$z[4]=Array("arclist","\r\n<li class=\"s\"><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n",5602,5799);
$z[4][4]['orderby']="pubdate";
$z[4][4]['row']="10";
$z[4][4]['typeid']="9";
$z[5]=Array("arclist","\r\n\r\n            <li class=\"s\"><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n",5996,6208);
$z[5][4]['orderby']="pubdate";
$z[5][4]['row']="10";
$z[5][4]['typeid']="10";
$z[6]=Array("include","",6745,6782);
$z[6][4]['filename']="footer.htm";

?>