<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",47,79);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("field","",175,204);
$z[2][4]['name']="position";
$z[3]=Array("arclist"," \r\n                <li class=\"li_e\"><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n",300,451);
$z[3][4]['typeid']="2";
$z[3][4]['row']="10";
$z[3][4]['titlelen']="50";
$z[4]=Array("global","",568,600);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("include","",3987,4024);
$z[5][4]['filename']="footer.htm";

?>