<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",47,79);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("field","",175,204);
$z[2][4]['name']="position";
$z[3]=Array("arclist"," \r\n                <li class=\"li_e\"><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n",300,451);
$z[3][4]['typeid']="2";
$z[3][4]['row']="10";
$z[3][4]['titlelen']="50";
$z[4]=Array("global","",568,600);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("list","\r\n\r\n                \r\n\r\n    <li><a style=\"color:#444; font-size:14px;\" href=\"[field:arcurl/]\"><span style=\"float:right; font-size:14px;\">[field:pubdate function=\"GetDateTimeMK(@me)\"/]</span><font style=\"color:;\">[field:title/]</font></a></li>\r\n",1761,2042);
$z[5][4]['pagesize']="14";
$z[6]=Array("pagelist","",2204,2282);
$z[6][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",3196,3233);
$z[7][4]['filename']="footer.htm";

?>