<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",157,186);
$z[1][4]['name']="position";
$z[2]=Array("list","  \r\n<li>\r\n<li class=\"li_e\"><a href=\"[field:arcurl/]\" >[field:title/]</a></li>\r\n</li>\r\n",292,415);
$z[2][4]['pagesize']="2";
$z[3]=Array("global","",494,526);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("list","\r\n\r\n                \r\n\r\n    <li><a style=\"color:#444; font-size:14px;\" href=\"[field:arcurl/]\"><span style=\"float:right; font-size:14px;\">[field:pubdate function=\"GetDateTimeMK(@me)\"/]</span><font style=\"color:;\">[field:title/]</font></a></li>\r\n",1715,1996);
$z[4][4]['pagesize']="14";
$z[5]=Array("pagelist","",2158,2236);
$z[5][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",3169,3206);
$z[6][4]['filename']="footer.htm";

?>