<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("list","  \r\n<li>\r\n<li class=\"li_e\"><a href=\"[field:arcurl/]\" >[field:title/]</a></li>\r\n</li>\r\n",280,404);
$z[1][4]['pagesize']="12";
$z[2]=Array("global","",483,515);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("arclist","\r\n                      	<li> \r\n<img src=\"[field:picname/]\"/>\r\n<span style=\"display:block; margin:0 auto; text-align:center;\" ><a href=\"[field:arcurl/]\" style=\"width:auto !important; height: auto !important;background: none; padding: 0px 9px 0px 8px;\">[field:title/]</a></span>\r\n\r\n            </li>\r\n",1727,2122);
$z[3][4]['row']="12";
$z[3][4]['imgheight']="175";
$z[3][4]['imgwidth']="220";
$z[3][4]['titlelen']="30";
$z[3][4]['infolen']="80";
$z[4]=Array("include","",2226,2263);
$z[4][4]['filename']="footer.htm";

?>